name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: 
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Github'
        uses: actions/checkout@main
      - name: 'Log in to GHCR'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: 'Build/push image'
        run: |
          docker build . --tag ghcr.io/gnosticjade/auto-ytarchive-raw:latest
          docker push ghcr.io/gnosticjade/auto-ytarchive-raw:latest
